python3 exp4.py iris_17.dat > Logs/exp4_3/exp4_iris_17.log &&
python3 exp4.py iris_18.dat > Logs/exp4_3/exp4_iris_18.log &&
python3 exp4.py iris_19.dat > Logs/exp4_3/exp4_iris_19.log &&
python3 exp4.py glass.dat > Logs/exp4_3/exp4_glass.log &&
python3 exp4.py wine.dat > Logs/exp4_3/exp4_wine.log &&
python3 exp4.py ecoli.dat > Logs/exp4_3/exp4_ecoli.log &&
python3 exp4.py hepatitis.dat > Logs/exp4_3/exp4_hepatitis.log &&
python3 exp4.py heart.dat > Logs/exp4_3/exp4_heart.log &&
python3 exp4.py dermatology.dat > Logs/exp4_3/exp4_dermatology.log &&
python3 exp4.py auto.dat > Logs/exp4_3/exp4_auto.log &&
python3 exp4.py horseColic.dat > Logs/exp4_3/exp4_horseColic.log &&
python3 exp4.py pima.dat > Logs/exp4_3/exp4_pima.log &&
python3 exp4.py ionosphere.dat > Logs/exp4_3/exp4_ionosphere.log &&
python3 exp4.py flare.dat > Logs/exp4_3/exp4_flare.log &&
python3 exp4.py cylBands.dat > Logs/exp4_3/exp4_cylBands.log &&
python3 exp4.py led.dat > Logs/exp4_3/exp4_led.log &&
python3 exp4.py ticTacToe.dat > Logs/exp4_3/exp4_ticTacToe.log &
